source_name: "工业IXPE发泡塑料生产线摄像头"
source_type: "video"
source_mode: "rtsp_video"
source_list:
  - name: "ixpe_camera_0"
    url: ""
    dir: "ixpe_0/"
    metadata:
      resolution: "540p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 1
    importance: 5
  - name: "ixpe_camera_1"
    url: ""
    dir: "ixpe_1/"
    metadata:
      resolution: "540p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 1
    importance: 4

