source_name: "发泡塑料产线摄像头"
source_type: "video"
source_mode: "rtsp_video"
source_list:
  - name: "ixpe_camera_0"
    url: ""
    dir: "edge_eye_0/"
    metadata:
      resolution: "540p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 1
    importance: 5
#  - name: "ixpe_camera_1"
#    url: ""
#    dir: "edge_eye_1/"
#    metadata:
#      resolution: "540p"
#      fps: 30
#      encoding: "mp4v"
#      buffer_size: 1
#    importance: 4

