source_name: "钢材涡流"
source_type: "video"
source_mode: "rtsp_video"
source_list:
  - name: "waveform_source_0"
    url: ""
    dir: "waveform/"
    metadata:
      resolution: "1080p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 1
    importance: 5
